---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    type: be-type
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: be-type
    spec:
      containers:
      - name: be-container
        image: sakomws/backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: backend-srv
  labels:
    type: be-type
spec:
  ports:
  - name: be
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    type: be-type
