---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    type: fe-type
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: fe-type
    spec:
      containers:
      - name: fe-container
        image: sakomws/frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: BE_SRV_SERVICE_HOST
          value: backend-srv.default.svc.cluster.local
        - name: BE_SRV_SERVICE_PORT
          value: "80"

        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-srv
  labels:
    type: fe-type
spec:
  type: ClusterIP
  ports:
  - name: fe
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    type: fe-type
